export const PAYMENT_METHOD_WITHOUT_USING_FINANCIAL_SYSTEM = {
    code: "01",
    description: "SIN UTILIZACION DEL SISTEMA FINANCIERO"
}

export const PAYMENT_METHOD_DEBT_COMPENSATION = {
    code: "15",
    description: "COMPENSACIÓN DE DEUDAS"
}

export const PAYMENT_METHOD_DEBIT_CARD = {
    code: "16",
    description: "TARJETA DE DÉBITO"
}

export const PAYMENT_METHOD_CREDIT_CART = {
    code: "19",
    description: "TARJETA DE CRÉDITO"
}

export const PAYMENT_METHOD_ELECTRONIC_MONEY = {
    code: "17",
    description: "DINERO ELECTRÓNICO"
}

export const PAYMENT_METHOD_PREPAID_CARD = {
    code: "18",
    description: "TARJETA PREPAGO"
}
export const PAYMENT_METHOD_OTHERS_WITH_USE_FINANCIAL_SYSTEM = {
    code: "20",
    description: "OTROS CON UTILIZACIÓN DEL SISTEMA FINANCIERO"
}

export const PAYMENT_METHOD_ENDORSEMENT_TITLES = {
    code: "21",
    description: "ENDOSO DE TÍTULOS"
}

export const PAYMENT_METHODS = [
    PAYMENT_METHOD_WITHOUT_USING_FINANCIAL_SYSTEM,
    PAYMENT_METHOD_DEBT_COMPENSATION,
    PAYMENT_METHOD_DEBIT_CARD,
    PAYMENT_METHOD_ELECTRONIC_MONEY,
    PAYMENT_METHOD_PREPAID_CARD,
    PAYMENT_METHOD_CREDIT_CART,
    PAYMENT_METHOD_OTHERS_WITH_USE_FINANCIAL_SYSTEM,
    PAYMENT_METHOD_ENDORSEMENT_TITLES
]